name: clnapp
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1-alpha.3+6

environment:
  sdk: ">=2.15.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cln_grpc: ^0.0.1-beta.3
  cln_common: ^0.0.1-beta.3
  clightning_rpc: ^0.0.2-beta.5
  trash_component:
    git:
      url: https://github.com/vincenzopalazzo/trash
      path: packages/components
  get_it: ^7.2.0
  bottom_navy_bar: ^6.0.0
  trash_themes: ^0.0.3
  fixnum: ^1.0.1
  recase: ^4.0.0
  file_picker: ^5.0.1
  shared_preferences: ^2.0.15
  lnlambda: ^0.0.1-beta.7
  json_annotation: ^4.5.0
  flutter_launcher_icons: ^0.10.0
  bolt11_decoder: ^1.0.2
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.0.0
  json_serializable: ^6.2.0

dependency_overrides:
  cln_common:
    git:
      url: https://github.com/Harshit933/lndart.cln
      path: packages/cln_common
      ref: directory-fix

flutter:
  uses-material-design: true
  assets:
    - assets/images/exclamation.png
    - assets/images/scanner.png
    - assets/images/Checkmark.png
    - assets/images/downbutton.png
